# Generated by Django 6.0.6 on 2026-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_task_due_date_category_task_category_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', 'No recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', max_length=10),
        ),
    ]
